Ukol5
kubco2/filmovarka pull request #4
Opened 2016-10-26 11:20 UTC by kubco2

* Add 2 sections to main activity list
* download lists and pictures

2016-11-28 21:44 UTC, vandus commented on app/src/main/java/uco374386/movio2/pv256/fi/muni/cz/filmovarka/MovieFragment.java
> +        Picasso.with(getContext()).load(movie.getPosterUrl("w1280")).into((ImageView) rootView.findViewById(R.id.poster_image));
tento obrazok sa nacitava strasne dlho. nepostaci mensia velkost? myslim ze ta velkost by mala cca odpovedat vyslednej a toto je nejak moc. mozno tam dlho trva vysledna transformacia. skus pouzit mensiu.

2016-11-28 21:47 UTC, vandus requested changes
v detaili je obrazok s filmom zarovnany s coverom. mal by ho prekryvat. skus sa trochu pohrat s constraint layoutami a kotvami

2016-11-29 14:13 UTC, kubco2 commented
Dufam, ze som to v tom constraint layout urobil spravne, hral som sa s tym dost dlho, celkom to blbo v Android 2.2.2.

2017-01-08 12:24 UTC, vandus commented
V Android 2.2.2???!!! :-O

2017-01-08 12:26 UTC, vandus commented on app/src/main/AndroidManifest.xml
> +                <category android:name="android.intent.category.LAUNCHER"/>
pozor na taketo zmeny v commitoch. su zbytocne a mozu zapricinit, ze si reviewer nevsimne nejake dolezite veci.

2017-01-08 12:28 UTC, vandus commented on app/src/main/java/uco374386/movio2/pv256/fi/muni/cz/filmovarka/MainActivity.java
> +    }
tu by sa asi mali este refreshnut filmy, pretoze inak ten navigation drawer nefunguje...zakazala som vsetky kategorie a v zozname sa nic nezmenilo.

2017-01-08 12:29 UTC, vandus approved these changes

2017-01-08 14:42 UTC, merged